title: OpenDCS
url: "https://open-dcs.github.org" # the base hostname & protocol for your site
email: geoff.jay@gmail.com
author: Geoff Johnson <geoff.jay@gmail.com>
host: 0.0.0.0

description: >
  OpenDCS is a set of libraries and applications to create distributed control
  systems. Core features will include data acquisition, data logging, feedback
  control, and a configurable HMI utility.

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Makefile']

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: geoffjay
github_username:  open-dcs

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/_sass

paginate: 10

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
