title: OpenDCS
url: "https://open-dcs.github.org" # the base hostname & protocol for your site
email: geoff.jay@gmail.com
author: Geoff Johnson <geoff.jay@gmail.com>

description: >
  OpenDCS is a set of libraries and applications to create distributed control
  systems. Core features will include data acquisition, data logging, feedback
  control, and a configurable HMI utility.

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Makefile']

baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: geoffjay
github_username:  geoffjay

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
